"""Migración inicial permisos

Revision ID: 11e96428ff4c
Revises: 
Create Date: 2025-06-12 12:56:35.112667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e96428ff4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas_area_comun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horario', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salidas_vivienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=False),
    sa.Column('fecha_regreso', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salidas_vivienda')
    op.drop_table('reservas_area_comun')
    # ### end Alembic commands ###
