"""Migración inicial permisos

Revision ID: 1b6390b66e83
Revises: 11e96428ff4c
Create Date: 2025-06-12 12:59:25.850465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6390b66e83'
down_revision = '11e96428ff4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas_area_comun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('reservas_area_comun_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('salidas_vivienda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('salidas_vivienda_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salidas_vivienda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('salidas_vivienda_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id_usuario'])
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('reservas_area_comun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reservas_area_comun_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id_usuario'])
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
