"""add stock to actividades + inscripciones tabla

Revision ID: 646c2322fa63
Revises: d76c047df116
Create Date: 2025-07-14 15:46:43.648627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646c2322fa63'
down_revision = 'd76c047df116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_codigo_alumno_key'), type_='unique')
        batch_op.drop_column('codigo_alumno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_alumno', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('usuarios_codigo_alumno_key'), ['codigo_alumno'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
