"""Migración actualizar tabla usuarios y subir tabla asistencia

Revision ID: 9f3191a0934c
Revises: 817551ed2ad6
Create Date: 2025-06-12 23:42:21.914503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3191a0934c'
down_revision = '817551ed2ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('codigo_alumno', sa.String(length=20), nullable=False),
    sa.Column('hora_marcado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_alumno', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['codigo_alumno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codigo_alumno')

    op.drop_table('asistencias')
    # ### end Alembic commands ###
