"""Migración actualizar otra vez la tabla asistencia

Revision ID: d76c047df116
Revises: 01d781f2c441
Create Date: 2025-06-13 00:11:00.367866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76c047df116'
down_revision = '01d781f2c441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('asistencias_codigo_alumno_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.drop_column('codigo_alumno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_alumno', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('asistencias_codigo_alumno_fkey'), 'usuarios', ['codigo_alumno'], ['codigo_alumno'])
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
